<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Dev" name="org.colorMine.tests.ColorCalculatorTest" tests="4" failures="0" timestamp="2 Mar 2012 04:14:45 GMT" time="0.001" errors="1">
  <testcase name="getTriadic_GivenAColor_returnsTriadicColors" time="0.001" classname="org.colorMine.tests.ColorCalculatorTest">
    <error type="java.lang.AssertionError" message="expected:&lt;false&gt; but was:&lt;[Ljava.awt.Color;@37a001ff&gt;">
      <![CDATA[java.lang.AssertionError: expected:<false> but was:<[Ljava.awt.Color;@37a001ff>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
	at org.colorMine.tests.ColorCalculatorTest.getTriadic_GivenAColor_returnsTriadicColors(ColorCalculatorTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1022)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
    </error>
  </testcase> <!-- getTriadic_GivenAColor_returnsTriadicColors -->
  <testcase name="isComplement_GivenComplementaryColors_returnsTrue" time="0.000" classname="org.colorMine.tests.ColorCalculatorTest"/>
  <testcase name="getTriadic_GivenAColor_returnsTwoValues" time="0.000" classname="org.colorMine.tests.ColorCalculatorTest"/>
  <testcase name="isComplement_GivenNonComplementaryColors_returnsFalse" time="0.000" classname="org.colorMine.tests.ColorCalculatorTest"/>
</testsuite> <!-- org.colorMine.tests.ColorCalculatorTest -->
